version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/cicdproject # ec2서버에 어느 경로에 해당 코드를 저장할지

permissions:
  - object: /home/ec2-user/cicdproject
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
