version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/cicdproject # ec2서버에 어느 경로에 해당 코드를 저장할지
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root
